#!/usr/bin/env python3
"""
Screen sampled C3 poses for rigid-linker RFdiffusion design.

Screening system and default conditions:
- System: CK_XT_24 HA C3 trimer residues 1-525 fused to ChainABC scaffold
  residues 526-652, using chains A/B/C.
- Input: combined HA+scaffold mmCIF samples from
  rigid_design/align/ck_xt_24_scaffold_samples.
- Purpose: choose pre-RFdiffusion rigid linker candidates before designing a
  20 aa linker between HA residue 525 and scaffold residue 526.
- Default geometry model: CA-tangent continuity, with HA tangent CA524->CA525
  and scaffold tangent CA526->CA527.
- Default hard filters: endpoint distance 22-38 A, chain distance spread <=1 A,
  mean terminal tangent-to-endpoint angle <=70 deg, per-terminal angle <=75 deg,
  tangent bend angle <=25 deg, C3 axis angle <=2 deg, C3 axis offset <=1 A,
  terminal triangle side spread <=1 A.
- Ranking: primarily favors small HA/scaffold tangent bend, then consistent
  chain geometry and endpoint distances near the 30 A target.

The pipeline reads combined HA+scaffold mmCIF files generated by
sample_c3_axis.py, checks endpoint distances, C3 consistency, and terminal
CA-tangent continuity, then copies promising candidates to an output directory.
"""

from __future__ import annotations

import argparse
import csv
import math
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable

import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent
RIGID_DIR = SCRIPT_DIR.parent
ALIGN_DIR = RIGID_DIR / "align"


@dataclass(frozen=True)
class Atom:
    atom_name: str
    alt_id: str
    res_name: str
    label_seq_id: int
    chain_id: str
    x: float
    y: float
    z: float

    @property
    def coord(self) -> np.ndarray:
        return np.array([self.x, self.y, self.z], dtype=float)


@dataclass(frozen=True)
class Sample:
    sample_id: str
    path: Path
    meta: dict[str, str]


def parse_mmcif_atoms(path: Path) -> list[Atom]:
    atoms: list[Atom] = []
    with path.open("r", encoding="utf-8") as handle:
        for line in handle:
            if not line.startswith(("ATOM", "HETATM")):
                continue
            parts = line.strip().split()
            if len(parts) < 18:
                raise ValueError(f"Cannot parse atom line in {path}: {line.rstrip()}")
            atoms.append(
                Atom(
                    atom_name=parts[3],
                    alt_id=parts[4],
                    res_name=parts[5],
                    label_seq_id=int(parts[8]),
                    x=float(parts[10]),
                    y=float(parts[11]),
                    z=float(parts[12]),
                    chain_id=parts[16],
                )
            )
    if not atoms:
        raise ValueError(f"No ATOM/HETATM records found in {path}")
    return atoms


def normalize(vector: np.ndarray, label: str) -> np.ndarray:
    norm = float(np.linalg.norm(vector))
    if norm < 1e-8:
        raise ValueError(f"Cannot normalize near-zero {label}")
    return vector / norm


def angle_deg(a: np.ndarray, b: np.ndarray) -> float:
    a = normalize(a, "angle vector a")
    b = normalize(b, "angle vector b")
    return math.degrees(math.acos(float(np.clip(np.dot(a, b), -1.0, 1.0))))


def atom_coord(atoms: list[Atom], chain: str, seq: int, atom_name: str) -> np.ndarray:
    candidates = [
        atom
        for atom in atoms
        if atom.chain_id == chain
        and atom.label_seq_id == seq
        and atom.atom_name == atom_name
        and atom.alt_id in (".", "A", "?")
    ]
    if not candidates:
        raise ValueError(f"Missing {chain}:{seq}:{atom_name}")
    return candidates[0].coord


def ca_by_chain_residue(
    atoms: list[Atom],
    chains: list[str],
    min_seq: int,
    max_seq: int,
) -> dict[str, dict[int, np.ndarray]]:
    ca: dict[str, dict[int, np.ndarray]] = {chain: {} for chain in chains}
    for atom in atoms:
        if (
            atom.chain_id in ca
            and min_seq <= atom.label_seq_id <= max_seq
            and atom.atom_name == "CA"
            and atom.alt_id in (".", "A", "?")
        ):
            ca[atom.chain_id][atom.label_seq_id] = atom.coord
    return ca


def fit_c3_axis(
    atoms: list[Atom],
    chains: list[str],
    min_seq: int,
    max_seq: int,
) -> tuple[np.ndarray, np.ndarray]:
    ca = ca_by_chain_residue(atoms, chains, min_seq, max_seq)
    common_residues = set(ca[chains[0]])
    for chain in chains[1:]:
        common_residues &= set(ca[chain])
    if len(common_residues) < 2:
        raise ValueError(f"Need at least two shared CA residues in {min_seq}-{max_seq}")

    centers = np.array(
        [np.mean([ca[chain][seq] for chain in chains], axis=0) for seq in sorted(common_residues)]
    )
    axis_point = np.mean(centers, axis=0)
    _, _, vh = np.linalg.svd(centers - axis_point, full_matrices=False)
    axis = normalize(vh[0], "C3 axis")
    return axis_point, axis


def axis_alignment_metrics(
    ha_axis_point: np.ndarray,
    ha_axis: np.ndarray,
    scaffold_axis_point: np.ndarray,
    scaffold_axis: np.ndarray,
) -> tuple[float, float]:
    raw_angle = angle_deg(ha_axis, scaffold_axis)
    axis_angle = min(raw_angle, 180.0 - raw_angle)

    # The axes are expected to be nearly collinear. For near-parallel lines,
    # the perpendicular point-to-line distance is the stable offset metric.
    offset_vec = scaffold_axis_point - ha_axis_point
    axis_offset = np.linalg.norm(offset_vec - np.dot(offset_vec, ha_axis) * ha_axis)
    return axis_angle, float(axis_offset)


def triangle_side_spread(points: dict[str, np.ndarray], chains: list[str]) -> float:
    sides = [
        float(np.linalg.norm(points[chains[0]] - points[chains[1]])),
        float(np.linalg.norm(points[chains[1]] - points[chains[2]])),
        float(np.linalg.norm(points[chains[2]] - points[chains[0]])),
    ]
    return max(sides) - min(sides)


def spread(values: Iterable[float]) -> float:
    values = list(values)
    return max(values) - min(values)


def mean(values: Iterable[float]) -> float:
    values = list(values)
    return sum(values) / len(values)


def discover_samples(samples_dir: Path, summary_name: str) -> list[Sample]:
    summary_path = samples_dir / summary_name
    samples: list[Sample] = []
    if summary_path.exists():
        with summary_path.open("r", encoding="utf-8", newline="") as handle:
            for row in csv.DictReader(handle):
                sample_id = row.get("sample_id") or Path(row.get("file", "")).stem
                raw_file = Path(row.get("file", ""))
                path = raw_file
                if not path.exists():
                    path = samples_dir / f"{sample_id}.cif"
                if not path.exists() and raw_file.name:
                    path = samples_dir / raw_file.name
                samples.append(Sample(sample_id=sample_id, path=path, meta=row))
    else:
        for path in sorted(samples_dir.glob("*.cif")):
            samples.append(Sample(sample_id=path.stem, path=path, meta={}))
    if not samples:
        raise ValueError(f"No samples found in {samples_dir}")
    return samples


def terminal_vectors(
    atoms: list[Atom],
    chain: str,
    ha_end_residue: int,
    scaffold_start_residue: int,
    orientation_mode: str,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    ha_c = atom_coord(atoms, chain, ha_end_residue, "C")
    scaffold_n = atom_coord(atoms, chain, scaffold_start_residue, "N")
    linker = scaffold_n - ha_c

    if orientation_mode == "terminal-bond":
        ha_ca = atom_coord(atoms, chain, ha_end_residue, "CA")
        scaffold_ca = atom_coord(atoms, chain, scaffold_start_residue, "CA")
        ha_exit = ha_c - ha_ca
        scaffold_entry = scaffold_ca - scaffold_n
    elif orientation_mode == "ca-tangent":
        ha_prev_ca = atom_coord(atoms, chain, ha_end_residue - 1, "CA")
        ha_ca = atom_coord(atoms, chain, ha_end_residue, "CA")
        scaffold_ca = atom_coord(atoms, chain, scaffold_start_residue, "CA")
        scaffold_next_ca = atom_coord(atoms, chain, scaffold_start_residue + 1, "CA")
        ha_exit = ha_ca - ha_prev_ca
        scaffold_entry = scaffold_next_ca - scaffold_ca
    else:
        raise ValueError(f"Unsupported orientation mode: {orientation_mode}")

    return ha_c, scaffold_n, linker, ha_exit, scaffold_entry


def evaluate_sample(sample: Sample, args: argparse.Namespace, chains: list[str]) -> dict[str, object]:
    if not sample.path.exists():
        raise FileNotFoundError(f"Cannot find sample CIF for {sample.sample_id}: {sample.path}")
    atoms = parse_mmcif_atoms(sample.path)

    distances: dict[str, float] = {}
    ha_angles: dict[str, float] = {}
    scaffold_angles: dict[str, float] = {}
    bend_angles: dict[str, float] = {}
    ha_c_points: dict[str, np.ndarray] = {}
    scaffold_n_points: dict[str, np.ndarray] = {}

    for chain in chains:
        ha_c, scaffold_n, linker, ha_exit, scaffold_entry = terminal_vectors(
            atoms,
            chain,
            args.ha_end_residue,
            args.scaffold_start_residue,
            args.orientation_mode,
        )
        ha_c_points[chain] = ha_c
        scaffold_n_points[chain] = scaffold_n
        distances[chain] = float(np.linalg.norm(linker))
        ha_angles[chain] = angle_deg(ha_exit, linker)
        scaffold_angles[chain] = angle_deg(scaffold_entry, linker)
        bend_angles[chain] = angle_deg(ha_exit, scaffold_entry)

    ha_axis_point, ha_axis = fit_c3_axis(atoms, chains, args.ha_min_residue, args.ha_end_residue)
    scaffold_axis_point, scaffold_axis = fit_c3_axis(
        atoms,
        chains,
        args.scaffold_start_residue,
        args.scaffold_max_residue,
    )
    c3_axis_angle, c3_axis_offset = axis_alignment_metrics(
        ha_axis_point,
        ha_axis,
        scaffold_axis_point,
        scaffold_axis,
    )

    distance_values = list(distances.values())
    ha_angle_values = list(ha_angles.values())
    scaffold_angle_values = list(scaffold_angles.values())
    terminal_angle_values = ha_angle_values + scaffold_angle_values
    bend_angle_values = list(bend_angles.values())
    distance_mean = mean(distance_values)
    distance_spread = spread(distance_values)
    ha_angle_spread = spread(ha_angle_values)
    scaffold_angle_spread = spread(scaffold_angle_values)
    angle_spread = max(ha_angle_spread, scaffold_angle_spread)
    terminal_angle_mean = mean(terminal_angle_values)
    terminal_angle_max = max(terminal_angle_values)
    bend_angle_mean = mean(bend_angle_values)
    bend_angle_max = max(bend_angle_values)
    ha_triangle_spread = triangle_side_spread(ha_c_points, chains)
    scaffold_triangle_spread = triangle_side_spread(scaffold_n_points, chains)

    failures: list[str] = []
    if min(distance_values) < args.min_distance or max(distance_values) > args.max_distance:
        failures.append("endpoint_distance_out_of_range")
    if distance_spread > args.max_distance_spread:
        failures.append("chain_distance_inconsistent")
    if max(ha_angle_values) > args.max_ha_exit_angle:
        failures.append("ha_exit_angle_too_large")
    if max(scaffold_angle_values) > args.max_scaffold_entry_angle:
        failures.append("scaffold_entry_angle_too_large")
    if terminal_angle_mean > args.max_mean_terminal_angle:
        failures.append("mean_terminal_angle_too_large")
    if bend_angle_max > args.max_bend_angle:
        failures.append("tangent_bend_angle_too_large")
    if angle_spread > args.max_angle_spread:
        failures.append("chain_angle_inconsistent")
    if c3_axis_angle > args.max_axis_angle:
        failures.append("c3_axis_angle_inconsistent")
    if c3_axis_offset > args.max_axis_offset:
        failures.append("c3_axis_offset_too_large")
    if max(ha_triangle_spread, scaffold_triangle_spread) > args.max_triangle_side_spread:
        failures.append("terminal_triangle_not_c3_like")

    endpoint_target_delta = (
        abs(distance_mean - args.target_distance) if args.target_distance > 0.0 else 0.0
    )
    terminal_angle_target_delta = abs(terminal_angle_mean - args.target_terminal_angle)
    if args.orientation_mode == "ca-tangent":
        score = (
            3.0 * bend_angle_mean
            + 1.5 * bend_angle_max
            + 2.0 * distance_spread
            + 1.25 * endpoint_target_delta
            + 1.0 * terminal_angle_target_delta
            + 2.0 * angle_spread
            + 5.0 * c3_axis_angle
            + 2.0 * c3_axis_offset
        )
    else:
        score = (
            terminal_angle_mean
            + 0.25 * bend_angle_mean
            + 2.0 * angle_spread
            + 5.0 * c3_axis_angle
            + 0.25 * distance_spread
            + 0.05 * distance_mean
        )

    row: dict[str, object] = {
        "sample_id": sample.sample_id,
        "source_file": str(sample.path),
        "pass": not failures,
        "fail_reasons": ";".join(failures),
        "score": score,
        "z_shift_A": sample.meta.get("z_shift_A", ""),
        "rotation_deg": sample.meta.get("rotation_deg", ""),
        "endpoint_mean_A": distance_mean,
        "endpoint_min_A": min(distance_values),
        "endpoint_max_A": max(distance_values),
        "endpoint_spread_A": distance_spread,
        "endpoint_target_delta_A": endpoint_target_delta,
        "ha_exit_angle_mean_deg": mean(ha_angle_values),
        "ha_exit_angle_max_deg": max(ha_angle_values),
        "ha_exit_angle_spread_deg": ha_angle_spread,
        "scaffold_entry_angle_mean_deg": mean(scaffold_angle_values),
        "scaffold_entry_angle_max_deg": max(scaffold_angle_values),
        "scaffold_entry_angle_spread_deg": scaffold_angle_spread,
        "terminal_angle_mean_deg": terminal_angle_mean,
        "terminal_angle_max_deg": terminal_angle_max,
        "terminal_angle_target_delta_deg": terminal_angle_target_delta,
        "bend_angle_mean_deg": bend_angle_mean,
        "bend_angle_max_deg": bend_angle_max,
        "c3_axis_angle_deg": c3_axis_angle,
        "c3_axis_offset_A": c3_axis_offset,
        "ha_terminal_triangle_spread_A": ha_triangle_spread,
        "scaffold_terminal_triangle_spread_A": scaffold_triangle_spread,
    }
    for chain in chains:
        row[f"endpoint_{chain}_A"] = distances[chain]
        row[f"ha_exit_angle_{chain}_deg"] = ha_angles[chain]
        row[f"scaffold_entry_angle_{chain}_deg"] = scaffold_angles[chain]
        row[f"bend_angle_{chain}_deg"] = bend_angles[chain]
    return row


def write_csv(path: Path, rows: list[dict[str, object]]) -> None:
    if not rows:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def copy_candidates(
    candidate_rows: list[dict[str, object]],
    candidates_dir: Path,
) -> list[dict[str, object]]:
    candidates_dir.mkdir(parents=True, exist_ok=True)
    for old_file in candidates_dir.glob("rank_*_*.cif"):
        old_file.unlink()
    copied_rows: list[dict[str, object]] = []
    for rank, row in enumerate(candidate_rows, start=1):
        source = Path(str(row["source_file"]))
        copied = candidates_dir / f"rank_{rank:03d}_{source.name}"
        shutil.copy2(source, copied)
        out_row = dict(row)
        out_row["rank"] = rank
        out_row["copied_file"] = str(copied)
        copied_rows.append(out_row)
    return copied_rows


def make_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Filter C3 HA-scaffold poses for RFdiffusion rigid-linker design."
    )
    parser.add_argument("--samples-dir", type=Path, default=ALIGN_DIR / "ck_xt_24_scaffold_samples")
    parser.add_argument("--summary-name", default="summary.csv")
    parser.add_argument("--outdir", type=Path, default=ALIGN_DIR / "ck_xt_24_linker_candidates")
    parser.add_argument("--chains", default="A,B,C")
    parser.add_argument("--ha-min-residue", type=int, default=1)
    parser.add_argument("--ha-end-residue", type=int, default=525)
    parser.add_argument("--scaffold-start-residue", type=int, default=526)
    parser.add_argument("--scaffold-max-residue", type=int, default=652)
    parser.add_argument(
        "--orientation-mode",
        choices=["terminal-bond", "ca-tangent"],
        default="ca-tangent",
        help="terminal-bond uses HA CA->C and scaffold N->CA; ca-tangent uses terminal CA traces.",
    )
    parser.add_argument("--min-distance", type=float, default=22.0)
    parser.add_argument("--max-distance", type=float, default=38.0)
    parser.add_argument(
        "--target-distance",
        type=float,
        default=30.0,
        help="Preferred endpoint distance for ranking; set <=0 to disable this score term.",
    )
    parser.add_argument("--max-distance-spread", type=float, default=1.0)
    parser.add_argument(
        "--max-terminal-angle",
        type=float,
        default=None,
        help="Deprecated compatibility option. If set, applies to both HA exit and scaffold entry angles.",
    )
    parser.add_argument("--max-ha-exit-angle", type=float, default=None)
    parser.add_argument("--max-scaffold-entry-angle", type=float, default=None)
    parser.add_argument(
        "--target-terminal-angle",
        type=float,
        default=60.0,
        help="Preferred CA-tangent to endpoint-vector angle used only for ca-tangent ranking.",
    )
    parser.add_argument(
        "--max-mean-terminal-angle",
        type=float,
        default=None,
        help="Defaults are mode-specific: 70 deg for ca-tangent, 40 deg for terminal-bond.",
    )
    parser.add_argument(
        "--max-bend-angle",
        type=float,
        default=None,
        help="Defaults are mode-specific: 25 deg for ca-tangent, 70 deg for terminal-bond.",
    )
    parser.add_argument("--max-angle-spread", type=float, default=8.0)
    parser.add_argument("--max-axis-angle", type=float, default=2.0)
    parser.add_argument("--max-axis-offset", type=float, default=1.0)
    parser.add_argument("--max-triangle-side-spread", type=float, default=1.0)
    parser.add_argument("--no-copy", action="store_true", help="Only write CSV reports")
    return parser


def main() -> None:
    args = make_parser().parse_args()
    ca_tangent_mode = args.orientation_mode == "ca-tangent"
    if args.max_ha_exit_angle is None:
        args.max_ha_exit_angle = (
            args.max_terminal_angle
            if args.max_terminal_angle is not None
            else (75.0 if ca_tangent_mode else 60.0)
        )
    if args.max_scaffold_entry_angle is None:
        args.max_scaffold_entry_angle = (
            args.max_terminal_angle
            if args.max_terminal_angle is not None
            else (75.0 if ca_tangent_mode else 65.0)
        )
    if args.max_mean_terminal_angle is None:
        args.max_mean_terminal_angle = 70.0 if ca_tangent_mode else 40.0
    if args.max_bend_angle is None:
        args.max_bend_angle = 25.0 if ca_tangent_mode else 70.0

    chains = [chain.strip() for chain in args.chains.split(",") if chain.strip()]
    if len(chains) != 3:
        raise ValueError("--chains must contain exactly three chain IDs")

    samples = discover_samples(args.samples_dir, args.summary_name)
    rows: list[dict[str, object]] = []
    for sample in samples:
        try:
            rows.append(evaluate_sample(sample, args, chains))
        except Exception as exc:
            rows.append(
                {
                    "sample_id": sample.sample_id,
                    "source_file": str(sample.path),
                    "pass": False,
                    "fail_reasons": f"evaluation_error:{exc}",
                    "score": float("inf"),
                }
            )

    rows.sort(key=lambda row: (not bool(row["pass"]), float(row["score"])))
    passed = [row for row in rows if bool(row["pass"])]
    copied = [] if args.no_copy else copy_candidates(passed, args.outdir / "cif")

    all_report = args.outdir / "screened_summary.csv"
    candidates_report = args.outdir / "candidates.csv"
    write_csv(all_report, rows)
    write_csv(candidates_report, copied if copied else passed)

    print(f"Screened {len(rows)} poses from {args.samples_dir}")
    print(f"Passed: {len(passed)}")
    print(f"All metrics: {all_report}")
    print(f"Candidates: {candidates_report}")
    if not args.no_copy:
        print(f"Copied CIFs: {args.outdir / 'cif'}")


if __name__ == "__main__":
    main()
